# ===============================
# JWT CONFIGURATION
# ===============================
jwt.secret=MySuperStrongSecretKey1234567890987654321
spring.jwt.expired-duration=900
spring.jwt.refreshable-duration=604800
jwt.audience=iDocUsers
jwt.issuer=iDocAuthService